import type { Metadata } from "next";
import { IBM_Plex_Sans as FontSans } from "next/font/google"
import { Dela_Gothic_One as FontDisplay } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster"

import { cn } from "@/lib/utils"

const fontSans = FontSans({
    subsets: ["latin","cyrillic-ext"],
    weight: ["100","200","300","400","500","600","700"],
    style: ["normal","italic"],
    variable: "--font-sans",
})

const fontDisplay = FontDisplay({
    subsets: ["cyrillic","latin"],
    weight: "400",
    variable: "--font-display"
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(
                "min-h-screen bg-white font-sans antialiased",
                fontSans.variable,
                fontDisplay.className
            )}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
